
name: Unzip and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip the file
        run: unzip -o "Download.zip"

      - name: List files for debugging
        run: ls -laR

      - name: Commit unzipped files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-commit unzipped files"
          file_pattern: "*"
